#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir -p constant/triSurface
tar -zxf shuttle.stl.tar.gz -C constant/triSurface/.

runApplication blockMesh # create the mesh
runApplication checkMesh # check the mesh

runApplication surfaceFeatures # feature extraction 
runApplication snappyHexMesh -overwrite  # snappyHexMesh 

#------------------------------------------------------------------------------
