#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir -p constant/triSurface
gmsh meshSTEP.geo
cp -r shuttle.stl constant/triSurface

runApplication blockMesh # create the mesh
runApplication checkMesh # check the mesh

runApplication surfaceFeatures # feature extraction 
runApplication decomposePar # decompose the domain

runParallel snappyHexMesh -overwrite  # snappyHexMesh 

runApplication reconstructParMesh -constant
rm -r proc*

#------------------------------------------------------------------------------
